project:
  type: website
  resources:
    - "css/"
    - "js/"
    - "*.html"
  output-dir: docs

website:
  title: "RNAseq bacteria-nematode interactions"
  sidebar:
    style: "docked"
    background: light
    search: true
    contents:
      - text: "i) Formatting RNAseq counts"
        file: R/01_read_format_featureCounts.qmd
      - text: "ii) Analysis and plotting"
        file: R/02_dge_function.qmd
   
format:
  html:
    theme:
      - cosmo
    # include table of contents
    toc: true
    # when printing dataframes use rmarkdown::paged_table())
    df-print: paged
    # set default dimensions for figures
    fig-width: 8
    fig-height: 6
    # tidy format R code upon render
    tidy: false
    # include line numbers in code blocks
    code-line-numbers: true
    # The code-link option enables hyper-linking of functions within code blocks to their online documentation:
    #code-link: true
    number-sections: true
    code-fold: show
    code-summary: "Show/hide code"
    code-tools: true
  
# auto: re-render only when source changes   
execute:
  freeze: false 
  
editor: source
